server:
  port: 8083

spring:
  datasource:
    # 数据库连接池 HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.0.3.4:3306/jy_fund_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dev_user
    password: dev_user@jy28%JK
    hikari:
      # 池中维护的最小空闲连接数
      minimum-idle: 5
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 15
      # 自动提交
      auto-commit: true
      # 连接允许在池中闲置的最长时间
      idle-timeout: 30000
      # 池中连接最长生命周期
      max-lifetime: 1800000
      # 等待来自池的连接的最大毫秒数
      connection-timeout: 30000
  cloud:
    consul:
      discovery:
        enabled: true #启用服务发现
        register: true #启用服务注册
        deregister: true #服务停止时取消注册
        healthCheckPath: /actuator/health #健康检查的路径
        healthCheckInterval: 10s #执行监控检查的频率
        serviceName: consul-producer
        # prefer-ip-address: true #表示注册时使用IP而不是hostname
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        # instance-id: ${spring.application.name} #${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

  rabbitmq:
    # vpn:10.0.2.3:45672 测试服务器：183.84.2.5:5762
    host: '10.0.1.46' # RabbitMQ 服务器地址
    port: 5762 # RabbitMQ 服务器端口
    username: 'picc_callback_test' # RabbitMQ 服务器用户
    password: 'S823cichege2R1tlbamA' # RabbitMQ 服务器密码
    virtual-host: '/cacmp/picc/callback'

feign:
  httpclient:
    enabled: false # 是否启用httpclient
    connection-timeout: 5000 # 请求连接超时时间（毫秒）
  okhttp:
    enabled: true # 是否启用httpok（性能比httpclient高）
  hystrix:
    enabled: true # 是否启用hystrix

logging:
  level:
    cn.freeFly.springcloud.feign.UserServiceFeignClient: DEBUG
    cn.freeFly.springcloud.feign.CustomizeServiceFeignClient: DEBUG

log:
  path: /logs
  proName: springboot
  rootLevel: debug